### PR TITLE
add vm_region_recurse

### PR DESCRIPTION
**Pull request by m9**
I've implemented mach_vm_region_recurse and want to share teh code.
Please review, and would be happy to share knowledge in this field:)
(I'm pretty new to this os x internals, but keen to dive in.)

### CODE REVIEW

**Comment by abarnert** [comment]
Rather than comment here, I've sent you an email; let me know how you want to proceed.

**Comment by abarnert** [comment]
You have more time and motivation deal with this than I do. I can help you if 
you run into problems with unfamiliar stuff, but I probably won't be 
contributing very much directly. So, maybe you should fork the project to your 
own github (and I'd edit my SO answer to point to your repo instead of mine), or 
alternatively I could give you access to trunk so you don't have to wait for me 
to merge your pulls? 

If you plan to get this to the point where it would be useful to others, you 
might also want to rename the project, unless you intend to wrap up a lot more 
of the Mach API (at least the messaging bits). And create a PyPI project, and so 
on.

Meanwhile, a few comments:

The mach_vm_region_recurse wrapper is a great place to start expanding this. I 
suppose ultimately you'll want to wrap up everything in mach_vm.h. You might 
also want to write some higher-level functions in Python, e.g., a region walker 
sort of like os.walk. In that case, I'd rename the C module to _mach and create 
a pure-Python wrapper mach that imports it.

I believe by using the mix of types and methods you've used, the result is only 
going to work in some combinations orf 32-bit vs. 64-bit Python on 32-bit vs. 
64-bit kernels. But the last time I dealt with this stuff seriously was in 10.4, 
when Intel was all 32-bit, and the 64-bit issue only came up on G5, so you'll 
have to do the research to figure it out.

Which reminds me, I was pretty sloppy with the types; making sure you do 
universal builds (which I think should always happen if you're using 
/usr/bin/python) and watching for warnings should catch any sloppiness that 
actually makes a difference, but you might want to make the assumptions about 
the sizes of mach types, etc., more explicit.

You're returning the vm_region_submap_info_64 struct to Python as an int. I 
don't know what that does, but it can't be too useful. There are a variety of 
ways to pass a C structure back to Python. The most common is to declare a 
native extension type, so you can create an instance of that type, copy the 
values into it, and return that instance to Python, but it's less work to just 
return a dict mapping the field names to values, or just return a tuple and then 
put a Python wrapper around the module (rename the C module to "_mach" and have 
a Python module "mach" that imports "_mach") that creates a Python object out of 
the tuple.

If you want to do too much of this stuff, you may want to look at starting over 
with something easier than a raw C extension, which gets pretty painful when 
you're wrapping more than a handful of simple extensions. Cython is very nice, 
but Boost.Python, SWIG, and SIP, not to mention doing it all from the Python 
side with ctypes, all have pros and cons.

----- Original Message ----

> From: Sergey Balbeko 
> reply@reply.github.com
> 
> To: abarnert abarnert@yahoo.com
> Sent: Wed, June 6, 2012 4:19:26 PM
> Subject: [pymach] add vm_region_recurse (#1)
> 
> I've implemented mach_vm_region_recurse and want to share teh code.
> Please  review, and would be happy to share knowledge in this field:)
> (I'm pretty new  to this os x internals, but keen to dive in.)
> 
> You can merge this Pull  Request by running:
> 
>   git pull https://github.com/balbeko/pymach vm_region_recurse
> 
> Or you can view,  comment on it, or merge it online at:
> 
>   https://github.com/abarnert/pymach/pull/1
> 
> -- Commit Summary  --
> - ignores and cleanup
> - remove testing code
> - implemented  vm_region_recurse
> - gitignore, Makefile added
> 
> -- File Changes  --
> 
> A .gitignore (6)
> A Makefile (9)
> M mach.c (26)
> 
> -- Patch  Links --
> 
>   https://github.com/abarnert/pymach/pull/1.patch
>   https://github.com/abarnert/pymach/pull/1.diff
> 
> ---
> 
> Reply to this  email directly or view it on GitHub:
> https://github.com/abarnert/pymach/pull/1

**Comment by m9** [comment]
Hello
Thanks for an answer
For now i have no strict plan of actions what i'm going to do next, i started to look all this things just from a simple willing to have some toolkit to learn things related to RE of mac apps. I'm not sure yet, maybe it will grow to some framework, or to some tool. Will see.
The problem is than os x internals are not the only thing i've just started too look at. Python is also pretty new for me(i'm a rubyist and nodejs guy mostly), so there is a lot of selfeducating coming for me here:) i'm not sure that i can handle all of that on the same time, but i have willing to continue. That struct and types issue is my fault, i see - just probably was tired and got too much of new infirmation, so mixed up things a bit in my head and missed such obv. thing. Will fix after a sleep - as it is already 6am here:)

If you are not going to continue development here - then i'd better to continue on my own repo.

Cheers,
 Sergey

**Comment by abarnert** [comment]
That's actually the same reason I learned about Python extensions, to wrap up 
some OS-internal stuff so I could play with it in an interpreted environment.

Anyway, you should definitely take a look at either Cython or Boost.Python, or 
ctypes instead of building an extension module in raw C level. There's a bit of 
extra stuff to learn at the start, but once you get going it's so much faster, 
and so much harder to screw up, that it pays off.

Good luck with your self-education, and if you hit any problems, ask me and I'll 
see if I can help.

----- Original Message ----

> From: Sergey Balbeko 
> reply@reply.github.com
> 
> To: abarnert abarnert@yahoo.com
> Sent: Wed, June 6, 2012 8:14:24 PM
> Subject: Re: [pymach] add vm_region_recurse (#1)
> 
> Hello
> Thanks for an answer
> For now i have no strict plan of actions what  i'm going to do next, i started 
> to look all this things just from a simple  willing to have some toolkit to 
> learn things related to RE of mac apps. I'm not  sure yet, maybe it will grow to 
> some framework, or to some tool. Will  see.
> The problem is than os x internals are not the only thing i've just  started 
> too look at. Python is also pretty new for me(i'm a rubyist and nodejs  guy 
> mostly), so there is a lot of selfeducating coming for me here:) i'm not  sure 
> that i can handle all of that on the same time, but i have willing to  continue. 
> That struct and types issue is my fault, i see - just probably was  tired and 
> got too much of new infirmation, so mixed up things a bit in my head  and missed 
> such obv. thing. Will fix after a sleep - as it is already 6am  here:)
> 
> If you are not going to continue development here - then i'd  better to 
> continue on my own repo.
> 
> Cheers,
>  Sergey
> 
> Sent from my  iPhone
>

**Comment by m9** [comment]
Спасибо:)

i hope i'll have enough strength to deal with that all thing.  

## 

Sergey Balbeko,  
Operations Engineer, Freelancer
Twitter: @balbeko
Skype: sergey.balbeko
Mobile: +380 (97) 028 77 55

пятница, июня 8, 2012 в 1:51 AM, abarnert написал:

> That's actually the same reason I learned about Python extensions, to wrap up  
> some OS-internal stuff so I could play with it in an interpreted environment.
> 
> Anyway, you should definitely take a look at either Cython or Boost.Python, or  
> ctypes instead of building an extension module in raw C level. There's a bit of  
> extra stuff to learn at the start, but once you get going it's so much faster,  
> and so much harder to screw up, that it pays off.
> 
> Good luck with your self-education, and if you hit any problems, ask me and I'll  
> see if I can help.
> 
> ----- Original Message ----
> 
> > From: Sergey Balbeko  
> > <reply@reply.github.com (mailto:reply@reply.github.com)>
> > 
> > To: abarnert <abarnert@yahoo.com (mailto:abarnert@yahoo.com)>
> > Sent: Wed, June 6, 2012 8:14:24 PM
> > Subject: Re: [pymach] add vm_region_recurse (#1)
> > 
> > Hello
> > Thanks for an answer
> > For now i have no strict plan of actions what i'm going to do next, i started  
> > to look all this things just from a simple willing to have some toolkit to  
> > learn things related to RE of mac apps. I'm not sure yet, maybe it will grow to  
> > some framework, or to some tool. Will see.
> > The problem is than os x internals are not the only thing i've just started  
> > too look at. Python is also pretty new for me(i'm a rubyist and nodejs guy  
> > mostly), so there is a lot of selfeducating coming for me here:) i'm not sure  
> > that i can handle all of that on the same time, but i have willing to continue.  
> > That struct and types issue is my fault, i see - just probably was tired and  
> > got too much of new infirmation, so mixed up things a bit in my head and missed  
> > such obv. thing. Will fix after a sleep - as it is already 6am here:)
> > 
> > If you are not going to continue development here - then i'd better to  
> > continue on my own repo.
> > 
> > Cheers,
> > Sergey
> > 
> > Sent from my iPhone
> >

**Pull request closed without merging**
